@startuml

' Классы:
'-------------

class User {
 - id: Number
 - email: String
 - password: String
 - name: String
 + register()
 + login()
 + ValidateEmail()
 + ValidatePass()
}

class Game {
 + fetchText()
 + inputText()
}

class Statistics {
 + stats7Days()
 + bestUsersAttempts()
 + setTopAttempts()
 + parseDate()
 + getAverage()
 + formatDate()
 + getLast7Dates()
 + drawBarDiagram()
 + setValues()
}

class Profile {
 + ValidateEmail()
 + ValidatePass()
 + saveButton()
 + cancelButton()
 + musicToogle()
}

class Lobby {
 + OpenModal()
 + CloseModal()
}
class Server {
 +app: express.Application
 +connection: mysql.Connection
 +PORT: number
 + isAuthenticated()

}

class Database {
}

class UserController {
 + connection: mysql.Connection
 + /api/data
 + /api/signin
 + /api/signup
 + /api/signout
 + /api/modalChange
 + /api/endgame
 + /public/game
 + /public
 + getMaxId()
 + updateUser()
 + addAttempt()
}

' Ассоциации:
'-------------

Lobby --> Game : ассоциация
Lobby --> Statistics : ассоциация
Lobby --> Profile : ассоциация
Game --> Server
Statistics --> Server
Profile --> User
User <--> Game
User --|> Statistics  : наследование

Server --|>  UserController : наследование
UserController --> Database : ассоциация