@startuml
start

:Приложение делает GET запрос на сервер, чтобы получить текст;
:Приложение выводит полученный текст на экран;

repeat
    :Пользователь вводит букву;
    if (Буква введена верно?) then (да)
        :Приложение подсвечивает её зелёным;
    else (нет)
        :Приложение подсвечивает её красным;
    endif
repeat while (Ввод текста не завершён?) is (да)

:Приложение выводит статистику о завершённой попытке на экране;
:Приложение отправляет данные о завершённой попытке на сервер;

if (Пользователь нажимает "играть дальше"?) then (да)
    :Приложение начинает игру с начала;
else (нет)
    :Приложение перенаправляет пользователя в главное меню;
endif

stop
@enduml