@startuml
start
:Пользователь изменяет данные\n в полях для ввода;
:Приложение проверяет данные на валидность на стороне клиента;
if (Данные валидны?) then (Да)
 :Приложение формирует json-файл с данными пользователя;
 :Приложение отправляет данные на сервер;
 :Приложение проверяет валидацию на стороне сервера;
 if (Данные валидны) then (Да)
    :Приложение обновляет данные пользователя в базе данных;
    :Приложение обновляет данные пользователя в личном кабинете;
    stop
 else (Нет)
    :Приложение выводит сообщение об ошибке;
    kill
 endif
else (Нет)
 :Приложение выводит сообщение об ошибке;
 kill
endif
@enduml