@startuml
start
:Пользователь вводит данные;
:Приложение проверяет данные на валидность на стороне клиента;
if (Данные валидны?) then (Да)
 :Приложение отправляет данные на сервер;
 :Приложение проверяет валидацию на стороне сервера;
 if (Данные валидны) then (Да)
    if (Пользователь с таким email существует?) then (Да)
      :Приложение выводит сообщение о \nсуществовании пользователя с такой почтой;
      kill
    else (Нет)
      :Приложение вносит данные в базу данных;
      :Приложение перенаправляет пользователя в лобби игры;
      stop
    endif
 else (Нет)
    :Приложение выводит сообщение об ошибке;
    kill
 endif
else (Нет)
 :Приложение выводит сообщение об ошибке;
 kill
endif
@enduml