@startuml
actor User
participant "JavaScript" as JS
participant "HTML DOM" as DOM
participant "Server" as Server
participant "Database" as DB

User -> DOM: Ввод символа
activate JS
JS -> DOM: Обращение к введённому символу
activate DOM
DOM --> JS: Получение введённого символа
deactivate DOM
JS -> JS: Проверка длины всех введённых символов
alt length < 2
    JS -> JS: Если длина меньше 2, то старт времени
else
    JS -> JS: Записываем текущую дату
    alt current time - start_time >= last_time - start_time
        JS -> JS: если прошла секунда, то записываем текущую скорость
        JS -> JS: Вносим скорость в speedList
        JS -> JS: Обновляем last_time
JS -> JS: Обрабатываем корректность ввода
JS -> DOM: Устанавливаем класс в зависимости от корректности ввода
activate DOM
DOM --> JS: Статус
deactivate DOM
activate User
JS -> User : Статус
User -> JS : Ввод последнего символа
deactivate User
activate JS
JS -> JS : Подсчёт статистики за попытку
JS -> JS :Создание объекта для отправки на сервер
JS -> Server : POST по адресу /api/endgame
deactivate JS
Server -> Database : Получаем последний id пользователя
Database -> Server : id
activate Server
Server -> Server : Текущее время
Server -> Database : Обновление данных в таблице Users 
Database -> Server : Статус
Server -> Database : Добавление попытки в таблицу Attempts
Database -> Server : Статус
Server -> JS : Статус
deactivate Server
activate JS
JS -> DOM : Вывода данных
DOM -> JS : Статус
JS -> JS : Запись данных в localStorage
JS -> JS : Создание диаграммы скорости
JS -> DOM : Вывод диаграммы
deactivate JS
activate DOM
DOM -> User 



deactivate JS
@enduml
