@startuml
start

:Приложение подгружает статистику пользователя с сервера и выводит её на экран;

if (Пользователь нажимает "показать все попытки"?) then (да)
    :Приложение делает запрос к серверу, чтобы получить все попытки;
    :Приложение выводит на экран список всех попыток с их статистикой;
else (Нет)
endif
if (Пользователь выбирает временной диапазон завершённых попыток?) then (да)
    :Приложение делает запрос к серверу, чтобы получить все попытки из указанного диапазона;
    :Приложение выводит на экран список всех отфильтрованных попыток с их статистикой;
else (Нет)
endif

stop
@enduml