@startuml

skinparam actorStyle awesome
actor Пользователь as g
package "Действия при входе" {
  usecase "Авторизация" as UC1
  usecase "Регистрация" as UC2
}
package "Элементы лобби" {
  usecase "Личный кабинет" as LK
  usecase "Режим игры" as GM
  usecase "Меню статистики" as SM
}
(Главное меню игры) as MM
g --> UC1
g --> UC2
UC1 --> MM
UC2 --> MM
MM --> LK
MM --> GM
MM --> SM

@enduml
